In [1]:
%pip install SyntheticControlMethods #Beware! Use venv

Collecting SyntheticControlMethods
  Using cached SyntheticControlMethods-1.1.17-py2.py3-none-any.whl
Collecting numpy>=1.17 (from SyntheticControlMethods)
  Using cached numpy-2.0.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting scipy>=1.4.1 (from SyntheticControlMethods)
  Using cached scipy-1.14.0-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting pandas>=1.1.2 (from SyntheticControlMethods)
  Using cached pandas-2.2.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting cvxpy>=1.1.7 (from SyntheticControlMethods)
  Using cached cvxpy-1.5.2-cp312-cp312-macosx_10_9_universal2.whl.metadata (8.9 kB)
Collecting matplotlib>=2.2.3 (from SyntheticControlMethods)
  Using cached matplotlib-3.9.1.post1-cp312-cp312-macosx_11_0_arm64.whl.metadata (11 kB)
Collecting jinja2>=2.10 (from SyntheticControlMethods)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting osqp>=0.6.2 (from cvxpy>=1.1.7->SyntheticControlMethods)
  Using cached osqp-0.6.7.post1-cp312-cp312-macosx_11_0_arm64.whl.metadata (1.9 kB)
Collecting ecos>=2 (from cvxpy>=1.1.7->SyntheticControlMethods)
  Using cached ecos-2.0.14-cp312-cp312-macosx_10_9_universal2.whl
Collecting clarabel>=0.5.0 (from cvxpy>=1.1.7->SyntheticControlMethods)
  Using cached clarabel-0.9.0-cp37-abi3-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl.metadata (4.8 kB)
Collecting scs>=3.2.4.post1 (from cvxpy>=1.1.7->SyntheticControlMethods)
  Using cached scs-3.2.6-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting MarkupSafe>=2.0 (from jinja2>=2.10->SyntheticControlMethods)
  Using cached MarkupSafe-2.1.5-cp312-cp312-macosx_10_9_universal2.whl.metadata (3.0 kB)
Collecting contourpy>=1.0.1 (from matplotlib>=2.2.3->SyntheticControlMethods)
  Using cached contourpy-1.2.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (5.8 kB)
Collecting cycler>=0.10 (from matplotlib>=2.2.3->SyntheticControlMethods)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=2.2.3->SyntheticControlMethods)
  Using cached fonttools-4.53.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (162 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib>=2.2.3->SyntheticControlMethods)
  Using cached kiwisolver-1.4.5-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.12/site-packages (from matplotlib>=2.2.3->SyntheticControlMethods) (24.1)
Collecting pillow>=8 (from matplotlib>=2.2.3->SyntheticControlMethods)
  Using cached pillow-10.4.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (9.2 kB)
Collecting pyparsing>=2.3.1 (from matplotlib>=2.2.3->SyntheticControlMethods)
  Using cached pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.12/site-packages (from matplotlib>=2.2.3->SyntheticControlMethods) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas>=1.1.2->SyntheticControlMethods)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas>=1.1.2->SyntheticControlMethods)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting qdldl (from osqp>=0.6.2->cvxpy>=1.1.7->SyntheticControlMethods)
  Using cached qdldl-0.1.7.post4-cp312-cp312-macosx_11_0_arm64.whl.metadata (1.7 kB)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=2.2.3->SyntheticControlMethods) (1.16.0)
Using cached cvxpy-1.5.2-cp312-cp312-macosx_10_9_universal2.whl (1.4 MB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Using cached matplotlib-3.9.1.post1-cp312-cp312-macosx_11_0_arm64.whl (7.8 MB)
Using cached numpy-2.0.1-cp312-cp312-macosx_14_0_arm64.whl (5.0 MB)
Using cached pandas-2.2.2-cp312-cp312-macosx_11_0_arm64.whl (11.3 MB)
Using cached scipy-1.14.0-cp312-cp312-macosx_14_0_arm64.whl (23.1 MB)
Using cached clarabel-0.9.0-cp37-abi3-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl (1.7 MB)
Using cached contourpy-1.2.1-cp312-cp312-macosx_11_0_arm64.whl (245 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.53.1-cp312-cp312-macosx_11_0_arm64.whl (2.2 MB)
Using cached kiwisolver-1.4.5-cp312-cp312-macosx_11_0_arm64.whl (64 kB)
Using cached MarkupSafe-2.1.5-cp312-cp312-macosx_10_9_universal2.whl (18 kB)
Using cached osqp-0.6.7.post1-cp312-cp312-macosx_11_0_arm64.whl (237 kB)
Using cached pillow-10.4.0-cp312-cp312-macosx_11_0_arm64.whl (3.4 MB)
Using cached pyparsing-3.1.2-py3-none-any.whl (103 kB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached scs-3.2.6-cp312-cp312-macosx_11_0_arm64.whl (93 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Using cached qdldl-0.1.7.post4-cp312-cp312-macosx_11_0_arm64.whl (98 kB)
Installing collected packages: pytz, tzdata, pyparsing, pillow, numpy, MarkupSafe, kiwisolver, fonttools, cycler, scipy, pandas, jinja2, contourpy, scs, qdldl, matplotlib, ecos, clarabel, osqp, cvxpy, SyntheticControlMethods
Successfully installed MarkupSafe-2.1.5 SyntheticControlMethods-1.1.17 clarabel-0.9.0 contourpy-1.2.1 cvxpy-1.5.2 cycler-0.12.1 ecos-2.0.14 fonttools-4.53.1 jinja2-3.1.4 kiwisolver-1.4.5 matplotlib-3.9.1.post1 numpy-2.0.1 osqp-0.6.7.post1 pandas-2.2.2 pillow-10.4.0 pyparsing-3.1.2 pytz-2024.1 qdldl-0.1.7.post4 scipy-1.14.0 scs-3.2.6 tzdata-2024.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
from SyntheticControlMethods import Synth
import numpy as np
import pandas as pd

In [2]:
data = pd.read_excel('data_28_06.xlsx')
data

,City,P_avg_per_m_sec,Population,P_avg_per_m_new,Expl_t_avg_sec,month,dummy_space,dummy_time,year,t,Reg_russian,Reg,Federal_district,lat,lon
0,Абаза,19412,12272,NaN,NaN,1,0,0,2019,1,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333
1,Абаза,12500,12272,NaN,NaN,5,0,0,2019,5,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333
2,Абаза,9114,12272,NaN,NaN,8,0,0,2019,8,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333
3,Абаза,13480,12272,NaN,NaN,11,0,0,2019,11,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333
4,Абаза,18473,12272,NaN,NaN,1,0,0,2020,13,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50423,Яхрома,110764,14011,NaN,43 д 17 ч,1,0,1,2024,61,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333
50424,Яхрома,125954,14011,NaN,NaN,2,0,1,2024,62,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333
50425,Яхрома,109608,14011,NaN,44 д 17 ч,3,0,1,2024,63,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333
50426,Яхрома,117442,14011,NaN,117 д 19 ч,4,0,1,2024,64,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333
50427,Яхрома,111994,14011,NaN,15 д 2 ч,5,0,1,2024,65,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333

In [3]:
tmp = data['City']+data['Reg']
cities_list  = list(set(list(tmp)))
cities_dict = {cities_list[i] :i for i in range(len(cities_list))}
data['city_id'] = tmp.apply(lambda x: cities_dict[x])

In [15]:
len(cities_list)

951

In [16]:
data

,City,P_avg_per_m_sec,Population,P_avg_per_m_new,Expl_t_avg_sec,month,dummy_space,dummy_time,year,t,Reg_russian,Reg,Federal_district,lat,lon,city_id
0,Абаза,19412,12272,NaN,NaN,1,0,0,2019,1,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333,137
1,Абаза,12500,12272,NaN,NaN,5,0,0,2019,5,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333,137
2,Абаза,9114,12272,NaN,NaN,8,0,0,2019,8,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333,137
3,Абаза,13480,12272,NaN,NaN,11,0,0,2019,11,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333,137
4,Абаза,18473,12272,NaN,NaN,1,0,0,2020,13,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333,137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50423,Яхрома,110764,14011,NaN,43 д 17 ч,1,0,1,2024,61,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333,65
50424,Яхрома,125954,14011,NaN,NaN,2,0,1,2024,62,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333,65
50425,Яхрома,109608,14011,NaN,44 д 17 ч,3,0,1,2024,63,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333,65
50426,Яхрома,117442,14011,NaN,117 д 19 ч,4,0,1,2024,64,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333,65
50427,Яхрома,111994,14011,NaN,15 д 2 ч,5,0,1,2024,65,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333,65

In [17]:
data.drop_duplicates(subset=['city_id', 't'])

,City,P_avg_per_m_sec,Population,P_avg_per_m_new,Expl_t_avg_sec,month,dummy_space,dummy_time,year,t,Reg_russian,Reg,Federal_district,lat,lon,city_id
0,Абаза,19412,12272,NaN,NaN,1,0,0,2019,1,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333,137
1,Абаза,12500,12272,NaN,NaN,5,0,0,2019,5,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333,137
2,Абаза,9114,12272,NaN,NaN,8,0,0,2019,8,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333,137
3,Абаза,13480,12272,NaN,NaN,11,0,0,2019,11,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333,137
4,Абаза,18473,12272,NaN,NaN,1,0,0,2020,13,Республика Хакасия,respublika-khakasiya,Сибирский,52.65000,90.08333,137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50423,Яхрома,110764,14011,NaN,43 д 17 ч,1,0,1,2024,61,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333,65
50424,Яхрома,125954,14011,NaN,NaN,2,0,1,2024,62,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333,65
50425,Яхрома,109608,14011,NaN,44 д 17 ч,3,0,1,2024,63,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333,65
50426,Яхрома,117442,14011,NaN,117 д 19 ч,4,0,1,2024,64,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333,65
50427,Яхрома,111994,14011,NaN,15 д 2 ч,5,0,1,2024,65,Московская область,moskovskaya-oblast,Центральный,56.28333,37.48333,65

In [18]:
#Получаю сбалансированнуюю панель по цене вторички
data.pivot(index='city_id', columns='t', values='P_avg_per_m_sec')

t,1,2,3,4,5,6,7,8,9,10,...,56,57,58,59,60,61,62,63,64,65
city_id,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,10841.0,NaN,NaN,9144.0,15000.0,NaN,NaN,NaN,...,34274.0,12340.0,NaN,33761.0,27580.0,34325.0,21139.0,23408.0,NaN,37667.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43462.0,43478.0,NaN,64000.0,45620.0,65606.0,48837.0,NaN,NaN,NaN
2,26909.0,25249.0,NaN,26826.0,32738.0,27514.0,24346.0,27419.0,19161.0,23687.0,...,44456.0,48717.0,49938.0,48295.0,45589.0,27718.0,48117.0,38675.0,64070.0,63891.0
3,25806.0,NaN,22965.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,38053.0,28205.0,43848.0,39102.0,40000.0,38229.0,40591.0,38512.0,47158.0,48077.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17648.0,11752.0,NaN,21521.0,23220.0,23278.0,27234.0,20484.0,21286.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,69097.0,69853.0,69903.0,68000.0,71034.0,70105.0,69374.0,72222.0,73742.0,73298.0,...,114386.0,117925.0,119128.0,120672.0,125000.0,127586.0,123223.0,125249.0,128044.0,NaN
947,24160.0,28023.0,26903.0,26836.0,25000.0,24731.0,25146.0,25357.0,24963.0,25758.0,...,38290.0,37821.0,38501.0,38889.0,40815.0,40462.0,43318.0,45024.0,42748.0,NaN
948,31315.0,35211.0,30865.0,33469.0,30806.0,34085.0,33250.0,29141.0,35984.0,30387.0,...,60461.0,64576.0,61947.0,62647.0,64103.0,58969.0,64521.0,72259.0,66519.0,69632.0
949,NaN,14250.0,20570.0,NaN,18293.0,25326.0,28623.0,NaN,25552.0,16216.0,...,33688.0,40312.0,38462.0,38497.0,35133.0,35909.0,43182.0,35593.0,32668.0,39976.0
950,30023.0,36616.0,38687.0,34310.0,20904.0,33824.0,34048.0,33997.0,37336.0,36454.0,...,61036.0,69767.0,63397.0,66333.0,76181.0,68195.0,75305.0,66811.0,71575.0,71651.0

In [19]:
data.drop_duplicates(subset=['city_id', 't']).dropna(subset = 'P_avg_per_m_sec').to_csv('arctic1807.csv')

# Тут переделать список тритмент и контрольных через city_id

In [6]:
#Получаю список городов, в которых было воздействие
treatment_cities = list(set(list(data.query('dummy_space == 1')['city_id'])))
#Датафрейм с не тритментом
data['control_flg'] = data['city_id'].apply(lambda x: 0 if x in treatment_cities else 1 )
control_df = data.query('control_flg == 1')

In [35]:
treatment_cities_df = pd.DataFrame({'City': treatment_cities, 'city_id':[cities_dict[city] for city in treatment_cities]})
treatment_cities_df.to_csv('treatment_cities.csv')

In [38]:
control_cities = list(set(list(data.query('dummy_space == 0')['City'])))
control_cities_df = pd.DataFrame({'City': control_cities, 'city_id':[cities_dict[city] for city in control_cities]})
control_cities_df.to_csv('control_cities.csv')

In [36]:
_i = 2
df = pd.concat([control_df.dropna(subset = 'P_avg_per_m_sec'), data.where(data.City == treatment_cities[i]).dropna(subset = 'City')]).dropna(subset = 'P_avg_per_m_sec').query('year >= 2023')
sc = Synth(df, 'P_avg_per_m_new', 'City', 't', 60, treatment_cities[i])

ValueError: cannot reshape array of size 16 into shape (17,1)

In [26]:
data.where(data.City == treatment_cities[i]).dropna(subset = 'City')

,City,P_avg_per_m_sec,Population,P_avg_per_m_new,Expl_t_avg_sec,month,dummy_space,dummy_time,year,t,Reg_russian,Reg,Federal_district,lat,lon,control_flg
45242,Усинск,42308.0,32182.0,NaN,81 д 4 ч,1.0,1.0,0.0,2019.0,1.0,Республика Коми,respublika-komi,Северо-Западный,65.995028,57.557139,0.0
45243,Усинск,42528.0,32182.0,NaN,58 д,2.0,1.0,0.0,2019.0,2.0,Республика Коми,respublika-komi,Северо-Западный,65.995028,57.557139,0.0
45244,Усинск,46667.0,32182.0,NaN,95 д 5 ч,3.0,1.0,0.0,2019.0,3.0,Республика Коми,respublika-komi,Северо-Западный,65.995028,57.557139,0.0
45245,Усинск,44928.0,32182.0,NaN,84 д 21 ч,4.0,1.0,0.0,2019.0,4.0,Республика Коми,respublika-komi,Северо-Западный,65.995028,57.557139,0.0
45246,Усинск,46997.0,32182.0,NaN,28 д 22 ч,5.0,1.0,0.0,2019.0,5.0,Республика Коми,respublika-komi,Северо-Западный,65.995028,57.557139,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45301,Усинск,49096.0,32182.0,NaN,201 д 11 ч,12.0,1.0,1.0,2023.0,60.0,Республика Коми,respublika-komi,Северо-Западный,65.995028,57.557139,0.0
45302,Усинск,51503.0,32182.0,NaN,83 д,1.0,1.0,1.0,2024.0,61.0,Республика Коми,respublika-komi,Северо-Западный,65.995028,57.557139,0.0
45303,Усинск,48435.0,32182.0,NaN,45 д 23 ч,2.0,1.0,1.0,2024.0,62.0,Республика Коми,respublika-komi,Северо-Западный,65.995028,57.557139,0.0
45304,Усинск,51771.0,32182.0,NaN,56 д 22 ч,3.0,1.0,1.0,2024.0,63.0,Республика Коми,respublika-komi,Северо-Западный,65.995028,57.557139,0.0
45305,Усинск,51607.0,32182.0,NaN,62 д 22 ч,4.0,1.0,1.0,2024.0,64.0,Республика Коми,respublika-komi,Северо-Западный,65.995028,57.557139,0.0